### ISSUE TITLE
constrictions on top of tongue shape

### ISSUE THREAD

**Issue by belm0** [PaulBatchelor/voc#3]
The voc docs state that direct call of sp_voc_set_diameter() should be avoided in favor of sp_voc_set_tongue_shape().  However in practice we need a way to conveniently set the tongue shape, yet also apply one or more vocal tract constrictions on top of that.

I haven't played with it much with the API yet, but it's not immediately clear how to achieve the tongue + constrictions capability of Pink Trombone with this API short of managing the constrictions manually (and perhaps adopting much logic from the Pink Trombone UI).

**Comment by PaulBatchelor** [comment]
sp_voc_set_tongue_shape() was only designed to mimic the XY control, and it's actually pretty limited in what it can do. I didn't bother porting any of the on-screen tract behavior because it didn't make sense without the UI. Under the hood, it's more or less a slider bank for each of the 45 individual vocal tract diameters. A few months ago, I made a [realtime voc demo using Nuklear](https://github.com/PaulBatchelor/voc_demo), where each vocal tract was mapped to a slider. Even with the clunky interface, I found you could mimic some of the PT behavior. If you added some sort of parabolic weights to nearby sliders, you could get something pretty similar.

Unfortunately, I think controlling the diameters manually with some sort of interactive slider bank is the best I can offer right now. The diameters can be manipulated directly using the data returned from sp_voc_get_track_diameters.

**Comment by belm0** [comment]
Would a reasonable goal be the ability to implement PT's UX on top of voc without a significant amount of domain logic?  The high level inputs to the synthesizer would be glottis freq, glottis on/off, tongue position, velum close/open, and a list of active constriction positions (corresponding to vocal tract touches in the UX).  I do think it's a suitable abstraction (i.e. makes sense without UI) and have witnessed artists successfully author to it.  Dealing with tract diameters and velum position directly is relatively low level and can be controlled internally by a simple model as PT does (based on constriction recovery speed, etc.).

In any case I'll need to interface voc to this abstraction for my use case.  Once I have an implementation maybe we can revisit whether it's suitable to build in.
